/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Common_layoutRouteImport } from './routes/_common_layout'
import { Route as Common_layoutIndexRouteImport } from './routes/_common_layout/index'
import { Route as Common_layoutSpacesRouteImport } from './routes/_common_layout/spaces'
import { Route as Common_layoutBookingsRouteImport } from './routes/_common_layout/bookings'
import { Route as Common_layoutAccountRouteImport } from './routes/_common_layout/account'

const Common_layoutRoute = Common_layoutRouteImport.update({
  id: '/_common_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Common_layoutIndexRoute = Common_layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Common_layoutRoute,
} as any)
const Common_layoutSpacesRoute = Common_layoutSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => Common_layoutRoute,
} as any)
const Common_layoutBookingsRoute = Common_layoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => Common_layoutRoute,
} as any)
const Common_layoutAccountRoute = Common_layoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => Common_layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof Common_layoutIndexRoute
  '/account': typeof Common_layoutAccountRoute
  '/bookings': typeof Common_layoutBookingsRoute
  '/spaces': typeof Common_layoutSpacesRoute
}
export interface FileRoutesByTo {
  '/account': typeof Common_layoutAccountRoute
  '/bookings': typeof Common_layoutBookingsRoute
  '/spaces': typeof Common_layoutSpacesRoute
  '/': typeof Common_layoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_common_layout': typeof Common_layoutRouteWithChildren
  '/_common_layout/account': typeof Common_layoutAccountRoute
  '/_common_layout/bookings': typeof Common_layoutBookingsRoute
  '/_common_layout/spaces': typeof Common_layoutSpacesRoute
  '/_common_layout/': typeof Common_layoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/bookings' | '/spaces'
  fileRoutesByTo: FileRoutesByTo
  to: '/account' | '/bookings' | '/spaces' | '/'
  id:
    | '__root__'
    | '/_common_layout'
    | '/_common_layout/account'
    | '/_common_layout/bookings'
    | '/_common_layout/spaces'
    | '/_common_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Common_layoutRoute: typeof Common_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_common_layout': {
      id: '/_common_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Common_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_common_layout/': {
      id: '/_common_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Common_layoutIndexRouteImport
      parentRoute: typeof Common_layoutRoute
    }
    '/_common_layout/spaces': {
      id: '/_common_layout/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof Common_layoutSpacesRouteImport
      parentRoute: typeof Common_layoutRoute
    }
    '/_common_layout/bookings': {
      id: '/_common_layout/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof Common_layoutBookingsRouteImport
      parentRoute: typeof Common_layoutRoute
    }
    '/_common_layout/account': {
      id: '/_common_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof Common_layoutAccountRouteImport
      parentRoute: typeof Common_layoutRoute
    }
  }
}

interface Common_layoutRouteChildren {
  Common_layoutAccountRoute: typeof Common_layoutAccountRoute
  Common_layoutBookingsRoute: typeof Common_layoutBookingsRoute
  Common_layoutSpacesRoute: typeof Common_layoutSpacesRoute
  Common_layoutIndexRoute: typeof Common_layoutIndexRoute
}

const Common_layoutRouteChildren: Common_layoutRouteChildren = {
  Common_layoutAccountRoute: Common_layoutAccountRoute,
  Common_layoutBookingsRoute: Common_layoutBookingsRoute,
  Common_layoutSpacesRoute: Common_layoutSpacesRoute,
  Common_layoutIndexRoute: Common_layoutIndexRoute,
}

const Common_layoutRouteWithChildren = Common_layoutRoute._addFileChildren(
  Common_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Common_layoutRoute: Common_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
