/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Common_layoutRouteImport } from './routes/_common_layout'
import { Route as Common_layoutIndexRouteImport } from './routes/_common_layout/index'
import { Route as Common_layoutSpacesIndexRouteImport } from './routes/_common_layout/spaces/index'
import { Route as Common_layoutBookingsIndexRouteImport } from './routes/_common_layout/bookings/index'
import { Route as Common_layoutSpacesIdRouteImport } from './routes/_common_layout/spaces/$id'
import { Route as Common_layoutBookingsIdRouteImport } from './routes/_common_layout/bookings/$id'

const Common_layoutRoute = Common_layoutRouteImport.update({
  id: '/_common_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Common_layoutIndexRoute = Common_layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Common_layoutRoute,
} as any)
const Common_layoutSpacesIndexRoute =
  Common_layoutSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => Common_layoutRoute,
  } as any)
const Common_layoutBookingsIndexRoute =
  Common_layoutBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => Common_layoutRoute,
  } as any)
const Common_layoutSpacesIdRoute = Common_layoutSpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => Common_layoutRoute,
} as any)
const Common_layoutBookingsIdRoute = Common_layoutBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => Common_layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof Common_layoutIndexRoute
  '/bookings/$id': typeof Common_layoutBookingsIdRoute
  '/spaces/$id': typeof Common_layoutSpacesIdRoute
  '/bookings/': typeof Common_layoutBookingsIndexRoute
  '/spaces/': typeof Common_layoutSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof Common_layoutIndexRoute
  '/bookings/$id': typeof Common_layoutBookingsIdRoute
  '/spaces/$id': typeof Common_layoutSpacesIdRoute
  '/bookings': typeof Common_layoutBookingsIndexRoute
  '/spaces': typeof Common_layoutSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_common_layout': typeof Common_layoutRouteWithChildren
  '/_common_layout/': typeof Common_layoutIndexRoute
  '/_common_layout/bookings/$id': typeof Common_layoutBookingsIdRoute
  '/_common_layout/spaces/$id': typeof Common_layoutSpacesIdRoute
  '/_common_layout/bookings/': typeof Common_layoutBookingsIndexRoute
  '/_common_layout/spaces/': typeof Common_layoutSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bookings/$id' | '/spaces/$id' | '/bookings/' | '/spaces/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookings/$id' | '/spaces/$id' | '/bookings' | '/spaces'
  id:
    | '__root__'
    | '/_common_layout'
    | '/_common_layout/'
    | '/_common_layout/bookings/$id'
    | '/_common_layout/spaces/$id'
    | '/_common_layout/bookings/'
    | '/_common_layout/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Common_layoutRoute: typeof Common_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_common_layout': {
      id: '/_common_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Common_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_common_layout/': {
      id: '/_common_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Common_layoutIndexRouteImport
      parentRoute: typeof Common_layoutRoute
    }
    '/_common_layout/spaces/': {
      id: '/_common_layout/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof Common_layoutSpacesIndexRouteImport
      parentRoute: typeof Common_layoutRoute
    }
    '/_common_layout/bookings/': {
      id: '/_common_layout/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof Common_layoutBookingsIndexRouteImport
      parentRoute: typeof Common_layoutRoute
    }
    '/_common_layout/spaces/$id': {
      id: '/_common_layout/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof Common_layoutSpacesIdRouteImport
      parentRoute: typeof Common_layoutRoute
    }
    '/_common_layout/bookings/$id': {
      id: '/_common_layout/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof Common_layoutBookingsIdRouteImport
      parentRoute: typeof Common_layoutRoute
    }
  }
}

interface Common_layoutRouteChildren {
  Common_layoutIndexRoute: typeof Common_layoutIndexRoute
  Common_layoutBookingsIdRoute: typeof Common_layoutBookingsIdRoute
  Common_layoutSpacesIdRoute: typeof Common_layoutSpacesIdRoute
  Common_layoutBookingsIndexRoute: typeof Common_layoutBookingsIndexRoute
  Common_layoutSpacesIndexRoute: typeof Common_layoutSpacesIndexRoute
}

const Common_layoutRouteChildren: Common_layoutRouteChildren = {
  Common_layoutIndexRoute: Common_layoutIndexRoute,
  Common_layoutBookingsIdRoute: Common_layoutBookingsIdRoute,
  Common_layoutSpacesIdRoute: Common_layoutSpacesIdRoute,
  Common_layoutBookingsIndexRoute: Common_layoutBookingsIndexRoute,
  Common_layoutSpacesIndexRoute: Common_layoutSpacesIndexRoute,
}

const Common_layoutRouteWithChildren = Common_layoutRoute._addFileChildren(
  Common_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Common_layoutRoute: Common_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
